### ISSUE TITLE
Try to fetch dockershim metrics data throws runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by angu2015** [brancz/kube-pod-exporter#1]
I tried to connect this exporter to dockershim by modifying the yaml file which you provided in the manifest.  It started successfully but when i tried to pull metrics by url - ip:portnumber/metrics. it throws an error as follows and container got restarted.

ts=2018-05-10T13:17:59.020518251Z caller=main.go:109 msg="dialing gRPC endpoint unix:///var/run/dockershim.sock"
ts=2018-05-10T13:17:59.020767033Z caller=main.go:146 msg="listening on :8080"
ts=2018-05-10T13:21:08.767618722Z caller=collector.go:86 component=collector err="rpc error: code = Unknown desc = not implemented"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x888080]

goroutine 35 [running]:
github.com/brancz/kube-pod-exporter/collector.(*collector).Collect(0xc4201a7500, 0xc420092cc0)
        /home/brancz/go/src/github.com/brancz/kube-pod-exporter/collector/collector.go:89 +0x400
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4200849a0, 0xc420092cc0, 0xa17320, 0xc4201a7500)
        /home/brancz/go/src/github.com/prometheus/client_golang/prometheus/registry.go:382 +0x61
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /home/brancz/go/src/github.com/prometheus/client_golang/prometheus/registry.go:380 +0x302

**Comment by brancz** [comment]
dockershim does not implement the CRI stats endpoints, which is why it fails, to my knowledge only cri-o and cri-containerd implement this API today
